name: npm publish package
run-name: ${{ github.actor }} pushed to package
on: [push]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' )
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build
        run: npm install

      - name: github_safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Publish
        uses: alishah151/colliding_balls@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
